{"name": "test_mul[except]", "status": "failed", "statusDetails": {"message": "AssertionError: assert '' == '请输入数字'\n  - 请输入数字", "trace": "self = <test_pytest.test_calc_new.TestCalc object at 0x7f87b359bfa0>, get_calc = <test_pytest.pythoncode.calculator.Calculator object at 0x7f87b3534910>\nget_muldatas = ['', 5, '请输入数字']\n\n    @pytest.mark.run(order=3)\n    def test_mul(self, get_calc, get_muldatas):\n        result = None\n        try:\n            # 调用mul函数,返回的结果保存在result里面\n            result = get_calc.mul(get_muldatas[0], get_muldatas[1])\n            # 判断result结果是否等于期望的值\n            if isinstance(result, float):\n                result = round(result, 2)\n        except Exception as e:\n            print(e)\n>       assert result == get_muldatas[2]\nE       AssertionError: assert '' == '请输入数字'\nE         - 请输入数字\n\ntest_calc_new.py:36: AssertionError"}, "parameters": [{"name": "get_muldatas", "value": "['', 5, '请输入数字']"}], "start": 1609753927623, "stop": 1609753927647, "uuid": "1db1cd51-9807-4f05-b9d3-bd287300ade7", "historyId": "e4dddebcae49ca802df5af4e17e75812", "testCaseId": "fe6bda14bd0e8d9a8af1eb7bd6c20851", "fullName": "test_calc_new.TestCalc#test_mul", "labels": [{"name": "tag", "value": "run(order=3)"}, {"name": "suite", "value": "test_calc_new"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "MacBook-Pro-2.local"}, {"name": "thread", "value": "43248-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calc_new"}]}