{"name": "test_add[except]", "status": "failed", "statusDetails": {"message": "AssertionError: assert None == '请输入数字'\n  +None\n  -'请输入数字'", "trace": "self = <test_pytest.test_calc_new.TestCalc object at 0x7f87b35344c0>, get_calc = <test_pytest.pythoncode.calculator.Calculator object at 0x7f87b3534910>\nget_datas = ['', 5, '请输入数字']\n\n    @pytest.mark.run(order=1)\n    def test_add(self, get_calc, get_datas):\n        result = None\n        try:\n            # 调用add函数,返回的结果保存在result里面\n            result = get_calc.add(get_datas[0], get_datas[1])\n            # 判断result结果是否等于期望的值\n            if isinstance(result, float):\n                result = round(result, 2)\n        except Exception as e:\n            print(e)\n>       assert result == get_datas[2]\nE       AssertionError: assert None == '请输入数字'\nE         +None\nE         -'请输入数字'\n\ntest_calc_new.py:22: AssertionError"}, "parameters": [{"name": "get_datas", "value": "['', 5, '请输入数字']"}], "start": 1609753927392, "stop": 1609753927394, "uuid": "b685a5ea-e119-44da-ac44-07910c282da0", "historyId": "58d2d73ea8b4de281c9d0010008c42ef", "testCaseId": "07d7074b11baf99ef0f511221e36f260", "fullName": "test_calc_new.TestCalc#test_add", "labels": [{"name": "tag", "value": "run(order=1)"}, {"name": "suite", "value": "test_calc_new"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "MacBook-Pro-2.local"}, {"name": "thread", "value": "43248-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calc_new"}]}